#!/usr/bin/env python3
"""Produce bench/results-summary.json from raw ghz output.

This is the missing link in the chain. bench/render.py proves the published
markdown matches bench/results-summary.json; this proves that file matches the
measurement, rather than having been typed in by hand.

    ./bench/all.sh                      # run everything, then call this
    python3 bench/summarize.py bench/results bench/results/rep1 rep2 rep3

Arguments: the operation-mix directory (containing set/get/incr/ping.json,
environment.json and stats.json written by bench/run.sh), then one directory
per sweep repetition (each containing cN.json and environment.json, written by
bench/sweep.sh).

Percentiles come from bench/report.py, which reads the raw per-request samples,
so p99.9 is a real measurement and there is exactly one percentile
implementation in the repository.
"""
import json
import pathlib
import statistics
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from report import summarize  # noqa: E402

OPS = ["get", "set", "incr", "ping"]

NOTE = ("Generated by bench/summarize.py from raw ghz runs; percentiles "
        "computed from per-request samples by bench/report.py. Raw ghz JSON "
        "(~731 MB) is not committed - regenerate with bench/all.sh.")


def load_env(path):
    p = pathlib.Path(path) / "environment.json"
    if not p.exists():
        raise SystemExit(
            f"missing {p}. Re-run bench/run.sh and bench/sweep.sh from this "
            f"revision; older runs wrote only the free-text environment.txt, "
            f"which nothing can parse.")
    return json.loads(p.read_text())


def operation_mix(opsdir):
    out = {}
    for name in OPS:
        path = pathlib.Path(opsdir) / f"{name}.json"
        if not path.exists():
            raise SystemExit(f"missing {path}; bench/run.sh did not complete")
        s = summarize(str(path))
        out[name] = {
            "rps": s["rps"],
            "count": s["count"],
            "ok": s["ok"],
            "p50": s["p50"], "p90": s["p90"], "p99": s["p99"],
            "p999": s["p999"], "p9999": s["p9999"], "max": s["max"],
            "status_codes": s["codes"],
        }
    return out


def sweep(repdirs):
    """Median across repetitions, per concurrency level.

    Levels are discovered from the files present rather than hardcoded, so a
    level that was measured is never silently dropped from the table -- which
    is what happened to c=800: bench/sweep.sh ran it and bench/aggregate.py's
    hardcoded list threw it away.
    """
    levels = set()
    for d in repdirs:
        for f in pathlib.Path(d).glob("c*.json"):
            try:
                levels.add(int(f.stem[1:]))
            except ValueError:
                continue
    if not levels:
        raise SystemExit(f"no cN.json files found in {repdirs}")

    out = {}
    for c in sorted(levels):
        runs, missing = [], []
        for d in repdirs:
            path = pathlib.Path(d) / f"c{c}.json"
            if path.exists():
                runs.append(summarize(str(path)))
            else:
                missing.append(str(path))
        if missing:
            print(f"warning: concurrency {c} measured in {len(runs)} of "
                  f"{len(repdirs)} repetitions ({', '.join(missing)} absent)",
                  file=sys.stderr)
        out[str(c)] = {
            "repetitions": len(runs),
            "rps_median": round(statistics.median(x["rps"] for x in runs), 1),
            "rps_runs": [round(x["rps"], 1) for x in runs],
            "p50_median_ms": round(statistics.median(x["p50"] for x in runs), 3),
            "p99_median_ms": round(statistics.median(x["p99"] for x in runs), 3),
            "p999_median_ms": round(statistics.median(x["p999"] for x in runs), 3),
            "errors": sum(x["count"] - x["ok"] for x in runs),
        }
    return out


def main(argv):
    if len(argv) < 3:
        raise SystemExit(__doc__)
    opsdir, repdirs = argv[1], argv[2:]

    env = load_env(opsdir)
    sweep_env = load_env(repdirs[0])
    if env.get("image_digest") != sweep_env.get("image_digest"):
        raise SystemExit(
            f"the operation mix measured {env.get('image_digest')} but the "
            f"sweep measured {sweep_env.get('image_digest')}. One summary must "
            f"describe one artefact; re-run both against the same image.")

    stats_path = pathlib.Path(opsdir) / "stats.json"
    stats = json.loads(stats_path.read_text()) if stats_path.exists() else {}

    summary = {
        "note": NOTE,
        "environment": env,
        "operation_mix": operation_mix(opsdir),
        "get_concurrency_sweep": sweep(repdirs),
        "server_stats_after_run": stats,
    }
    json.dump(summary, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main(sys.argv)
